const key_words = [
    [
        "Limpeza",
        "Faxina",
        "Diarista",
        "Empregada",
        "Arrumar",
        "casa",
        "Arrumadeira",
        "Faxineira",
        "Doméstica"
    ],
    [
        "Instalar",
        "Sistema",
        "Informática",
        "ti",
        "Windows",
        "Formatação",
        "Notebook",
        "Técnico",
        "Reparo",
        "placas",
        "Instalação",
        "softwares",
        "Upgrade",
        "Troca",
        "HD",
        "Serviços"
    ],
    [
        "Cabelo",
        "Cabelereiro",
        "Corte",
        "Barbeiro",
        "Barbearia",
        "Barba",
        "Cronograma",
        "capilar",
        "Coloração",
        "Luzes",
        "Progressiva",
        "Botox",
        "capilar",
        "Escova"
    ],
    [
        "Grama",
        "Grameiro",
        "Aparador",
        "Jardim",
        "Jardineiro"
    ],
    [
        "Soluções",
        "Solução",
        "Tecnologia",
        "Inovação"
    ],
    [
        "Arte",
        "Design",
        "Banner",
        "Designer",
        "Design",
        "gráfico",
        "Desenho",
        "Desenhista",
        "Logo",
        "Logotipo",
        "Marca",
        "gráfica"
    ],
    [
        "Pedreiro",
        "Obras",
        "Servente",
        "Obreiro",
        "Empreita",
        "Empreitada",
        "Acabamento",
        "Reboco"
    ],
    [
        "Confeiteira",
        "Confeitaria",
        "Doce",
        "Doceria",
        "Docinhos",
        "Beijinhos",
        "Brigadeiro",
        "Brigaderia",
        "Confete",
        "Bolo",
        "Boleira",
        "Cupcake"
    ],
    [
        "Cuidadora",
        "Babá",
        "Criança",
        "Mãe",
        "aluguel",
        "Home",
        "care"
    ],
    [
        "Eletricista",
        "Instalação",
        "Fios",
        "Fiação",
        "Montagem",
        "Padrão",
        "Quadro",
        "elétrico",
        "Trifásico",
        "Tomada",
        "Interruptores",
        "Lâmpadas",
        "Circuitos"
    ],
    [
        "Marmorista",
        "Mármore"
    ],
    [
        "Desenvolvedor",
        "Programador",
        "Programação",
        "Dados",
        "Código",
        "ti",
        "Aplicativo",
        "Site",
        "Interface",
        "Software",
        "Desenvolvimento",
        "Banco",
        "sistemas"
    ],
    [
        "Costureira",
        "Costura",
        "Roupa",
        "Vestido",
        "Conserto",
        "roupas"
    ],
    [
        "Massagem",
        "Massagista",
        "Terapia",
        "oriental",
        "Relaxamento",
        "Massoterapia",
        "Massoterapeuta"
    ],
    [
        "Estética",
        "Esteticista",
        "Drenagem",
        "Limpeza",
        "pele",
        "Depilação",
        "Depiladora",
        "Pump",
        "Sobrancelha",
        "Design",
        "sobrancelhas",
        "Beleza",
        "Botox"
    ],
    [
        "Refrigeração",
        "Ar",
        "Gelo",
        "Arcondicionado",
        "condicionado",
        "Higienização",
        "Manutenção"
    ],
    [
        "Sapateiro",
        "Graxeiro",
        "Sola",
        "Sapato",
        "Graxa",
        "Sandália",
        "Soleiro",
        "Sapataria"
    ],
    [
        "Antenista",
        "Antena",
        "Instalador",
        "Parabólica",
        "Tv",
        "Sinal",
        "Conexão",
        "Transmissão",
        "Técnico"
    ],
    [
        "Gazista",
        "Aquecedor",
        "Fogão",
        "Gás",
        "Vazamento",
        "Gasista"
    ],
    [
        "Calheiro",
        "Calhas",
        "Rufos",
        "Pingadeiras",
        "Coifas",
        "Telhado",
        "Telhados",
        "Telha"
    ],
    [
        "Manutenção",
        "Técnico",
        "Geladeira",
        "Freezer",
        "Arcondicionado",
        "Cervejeira",
        "Refrigeração",
        "Eletrodoméstico",
        "Máquina",
        "lavar",
        "Eletrotécnico"
    ],
    [
        "Segurança",
        "Alarme",
        "Privacidade",
        "24horas",
        "24",
        "horas",
        "Proteção",
        "Monitoramento",
        "Ronda",
        "Patrulha",
        "Comvigilância",
        "Vigia",
        "Vigilância"
    ],
    [
        "Manicure",
        "Pedicure",
        "Unhas",
        "Salão",
        "Beleza",
        "Esmalte",
        "Esmaltaria",
        "Unhas",
        "gel",
        "Spar",
        "pés"
    ],
    [
        "Engenheiro",
        "Engenharia",
        "Construção",
        "Obras",
        "Projetos",
        "técnicos",
        "Imóveis",
        "Gestão",
        "Residenciais",
        "Residência"
    ],
    [
        "Guitarra",
        "Música",
        "Guitarrista",
        "Banda",
        "Instrumentista"
    ],
    [
        "Dentista",
        "Dentes",
        "Odonto",
        "Odontologia",
        "Cirurgião",
        "Odontologista",
        "Resina",
        "Branqueamento",
        "Cárie",
        "Sorriso",
        "Dentário",
        "clareamento"
    ],
    [
        "Motoboy",
        "Moto ",
        "Boy",
        "Moto-boy",
        "Moto",
        "Motoqueiro",
        "Entrega",
        "Delivery"
    ],
    [
        "Construção",
        "Construtora",
        "Reformas",
        "Empreiteira"
    ],
    [
        "Higienização",
        "Higienizador",
        "Sofá",
        "Estofados"
    ],
    [
        "Pintor",
        "Pintura",
        "Tinta",
        "Parede",
        "Pintoria",
        "Massa",
        "corrida",
        "acrílica",
        "Texturas",
        "Granfino",
        "Grafiato"
    ],
    [
        "Contador",
        "Contabilidade",
        "MEI"
    ],
    [
        "Currículo",
        "Documentos",
        "rh",
        "Corporativo",
        "Cartões",
        "Xerox"
    ],
    [
        "Cuidadora",
        "Idosos",
        "Idoso",
        "Terceira",
        "idade"
    ],
    [
        "Artesão",
        "Vime"
    ],
    [
        "Cartomante",
        "Umbandista",
        "Candomblé",
        "Futuro",
        "Cartas",
        "Magia",
        "Espírito",
        "Espiritualidade",
        "Cigano",
        "Espirituais",
        "Cartomancia"
    ],
    [
        "Marido",
        "Aluguel",
        "Manutenção",
        "Faz ",
        "tudo",
        "Linha",
        "branca",
        "Concerto",
        "Conserto",
        "Bico",
        "Reforma",
        "geral "
    ],
    [
        "Polimento",
        "Automotivo"
    ],
    [
        "Marketing",
        "digital",
        "Gerenciamento",
        "Redes",
        "sociais",
        "mídia",
        "Publicidade",
        "propaganda"
    ],
    [
        "Piscineiro",
        "Piscina",
        "Cloro",
        "Limpeza",
        "pH",
        "Controle",
        "Higienização",
        "Aspiração  "
    ],
    [
        "Gestor",
        "tráfego",
        "Gerenciamento",
        "Anúncios",
        "Ads",
        "Gerenciar",
        "Público",
        "alvo",
        "pago",
        "Gestão"
    ]
]

export default key_words;